### ISSUE TITLE
Mac m1. docker运行报错 [ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.

### ISSUE THREAD

**Issue by hardwin1014** [buqiyuan/nest-admin#10]
大佬你好，我使用Windows的docker跑项目，没发现报错，使用Macm1  的docker跑的时候报一下错误，就单单按照文档上的步骤跑的。

ioredis官网说redis版本高于6，要设置username，我把docker里的redis降到了5版本，还是报错

没搞懂为什么window和Mac运行不一样

[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/81634902/201462094-822811fc-84ef-4533-ae0a-815b8b113c5c.png">

**Comment by buqiyuan** [comment]
不好意思~这个我也不清楚，没遇到过，按理说应该没有平台差异才对

**Comment by hardwin1014** [comment]
终于找到问题了，是因为我本地安装过redis，并且一直在启动，密码是root, 项目连接的不是docker中的redis，而是我本地的，停止本地的redis服务就没问题了
