### ISSUE TITLE
项目方便集成安全方面的库吗？

### ISSUE THREAD

**Issue by TangStudio** [buqiyuan/nest-admin#11]
## Feature request（新功能建议）
helmet和express rate limit都是express. js的库，而大佬你的这个项目底层是基于fastify的，请问fastify有类似的库吗？或者整个项目底层切换成express便捷吗？感谢

**Comment by buqiyuan** [comment]
如果你更习惯于使用 express 生态的库的话可以将项目里的 fastify 全部换成 express，因为是适配器模式，并且项目里也没有大量使用到 fastify 的独有特性，所以改换并成本不大。多翻一下官方文档就好了 基本你的问题文档里都有提到
- Q:  **请问fastify有类似的库吗**
   A: *官方有提供相应插件 [@fastify/helmet](https://docs.nestjs.com/security/helmet#use-with-fastify)*

**Comment by TangStudio** [comment]
感谢大佬的回答，另外我查了一下官方文档，文档在upload部分说是不兼容FastifyAdapter，是不是意味着如果是基于fastify的文件上传（非oss），只能依赖社区其它第三方库进行实现了呢？

**Comment by buqiyuan** [comment]
Upload 这部分我没有实践过，不过既然官方没有直接提供支持，那应该只能先寻求社区里比较推荐的第三方库进行兼容了

**Comment by wengfengtong** [comment]
实现上传可以使用@fastify/multipart这个第三方库，用法比较简单

**Comment by buqiyuan** [comment]
> 实现上传可以使用@fastify/multipart这个第三方库，用法比较简单

确实好使，已用上：https://github.com/buqiyuan/nest-admin/blob/2be3c8ebb3aa230faf622db27cfc846116085a4e/src/common/adapters/fastify.adapter.ts#L2-L18
