### ISSUE TITLE
你好，请问下，这个框架，本地文件上传怎么实现？

### ISSUE THREAD

**Issue by Yxliam** [buqiyuan/nest-admin#13]

**Comment by gslnzfq** [comment]
> 

目测文件是直接在前端推到七牛云，web端只负责查询和修改

**Comment by buqiyuan** [comment]
之前只做了七牛云上传，现在新增了[本地上传模块](https://github.com/buqiyuan/nest-admin/blob/main/src/modules/tools/upload/upload.controller.ts)
