### ISSUE TITLE
打包后 pnpm main.js 报错【TypeError: JwtStrategy requires a secret or key】

### ISSUE THREAD

**Issue by unz504** [buqiyuan/nest-admin#24]
![image](https://github.com/buqiyuan/nest-admin/assets/20376200/e50f227b-ede6-4ee7-9804-756bcb21c19f)

**Comment by unz504** [comment]
是我理解有问题吗 ，是不是不能打包的

**Comment by buqiyuan** [comment]
啊(⊙o⊙)…不是，开发环境能正常跑，打包肯定是没什么问题的，出现这个报错是因为`dist`目录下面没有 .env 文件，缺少相关的环境变量导致报错，因为打包的时候并不会将 .env 文件打包进去。

你切换到项目根目录执行以下命令再试试？
```bash
npx cross-env NODE_ENV=development node dist/main
```
总之有两点需要注意:
- 无论时开发环境还是生产环境，启动时都需要 `.env*`文件
- 需要指定环境变量 `NODE_ENV=development` 或 `NODE_ENV=production`

**Comment by unz504** [comment]
可以了
