### ISSUE TITLE
认证模块发送邮箱验证码失败，找不到模板文件，怎么解决？

### ISSUE THREAD

**Issue by yorkbbs** [buqiyuan/nest-admin#27]
`[Nest] 36164  - 2024/02/22 12:39:59    WARN [AllExceptionsFilter] 错误信息：(200) 验证码发送失败 Path: /api/auth/email/send
unhandledRejection:  Error: ENOENT: no such file or directory, open 'E:\dev\York\pc-service\dist\assets\templates\verification-code-zh.hbs'`

请问如何解决。谢谢

**Comment by buqiyuan** [comment]
感谢指出！`nestjs`默认不处理非 `ts/js` 文件，若要处理非 `ts` 资源，需要在 `nest-cli.json`中手动指定要复制的资源，[详见官方文档](https://docs.nestjs.com/cli/monorepo#assets)

**Comment by yorkbbs** [comment]
搞定了，非常感谢
`{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [{
      "name": "@nestjs/swagger",
      "options": {
        "introspectComments": true
      }
    }],
    "assets": [
      { "include": "**/*.hbs", "watchAssets": true }
    ]
  }
}
`

**Comment by yorkbbs** [comment]
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [{
      "name": "@nestjs/swagger",
      "options": {
        "introspectComments": true
      }
    }],
    "assets": [
      { "include": "**/*.hbs", "watchAssets": true }
    ]
  }
}
