### ISSUE TITLE
获取登录图片验证码API报500错误

### ISSUE THREAD

**Issue by XiAn-Bronc** [buqiyuan/nest-admin#3]
### 你好，我将后台程序运行起来，结果前台登录报500错误，具体错误见如下截图：
![image](https://user-images.githubusercontent.com/29709214/145720051-5bf50632-2fb8-4c22-a8fd-1246d68c8df7.png)
![image](https://user-images.githubusercontent.com/29709214/145720106-d595a22f-dc7f-4df0-9a53-24c0fb09a587.png)

   @buqiyuan 你知道这个什么原因导致的吗，望看到回复下，谢谢

**Comment by buqiyuan** [comment]
[原因见此issue](https://github.com/nestjs/nest/issues/8637)，解决方法降级安装class-transformer：yarn add class-transformer@0.4.0
