### ISSUE TITLE
在线用户列表

### ISSUE THREAD

**Issue by yuhao423** [buqiyuan/nest-admin#34]
## Feature request（新功能建议）
![image](https://github.com/buqiyuan/nest-admin/assets/76569582/084d61ab-fcc8-4b50-820a-4e0fd68466ad)

`nest-admin`是否需要加一个`在线用户列表`？，就像登录日志那样的表格。但是貌似`nest-admin`没有提供`个人设置模块`。

**Comment by buqiyuan** [comment]
是的，如果你有兴趣添加上述功能模块的话，欢迎 PR！

**Comment by yuhao423** [comment]
嗯嗯，可否给个联系方式，方便敲定一下原型图。

**Comment by buqiyuan** [comment]
微信：bqy_fe
