### ISSUE TITLE
大佬有关form表单接收数据的问题

### ISSUE THREAD

**Issue by sxlh0814** [buqiyuan/nest-admin#37]
## Feature request（新功能建议）

大佬,能不能写一个例子来接收form-data表单的数据,就是那种包含文件流跟表单数据的
包含file类型的文件跟jsonstring类型的表单数据,折腾了好几天搞不定.
以前使用的nest+express很容易实现,但是现在项目中使用nest+ Fastify有点搞不定

**Comment by buqiyuan** [comment]
请参考[官方文档](https://github.com/fastify/fastify-multipart?tab=readme-ov-file#handle-multiple-file-streams-and-fields)
<img width="911" alt="image" src="https://github.com/buqiyuan/nest-admin/assets/39730999/61e234b8-a9eb-4683-940c-456a5d3bba25">
<img width="683" alt="image" src="https://github.com/buqiyuan/nest-admin/assets/39730999/5bc0ec3e-640e-4580-93f0-2359a869495c">
