### ISSUE TITLE
如何部署到服务器

### ISSUE THREAD

**Issue by lsj980Ya** [buqiyuan/nest-admin#39]
请问如何部署到服务器

**Comment by buqiyuan** [comment]
首先确保你的 mysql、redis 服务正常可用，然后在 `.env.production` 文件中修改对应的连接配置。
然后在项目根目录执行 `pnpm build` 进行打包，打包完成之后执行 `pnpm start:prod` 查看程序是否正常运行，若程序正常运行，则可 `CTRL + C` 终止程序，然后全局安装 `pm2` node进程管理工具，安装完整后执行 `pnpm prod:pm2`即可。

**Comment by lsj980Ya** [comment]
那这样这个docker-composer 文件的用处就没了吗？能做到 cicd触发自动部署的吗

**Comment by buqiyuan** [comment]
> 部署的方式 N 种，你也没说清楚你的诉求呀。。。ps：请问如何部署到服务器 => 请问如何通过 docker 部署到服务器

当然可以做到 CI/CD 自动部署，不过是通过 SSH 远程登录到服务器进行部署操作。

CI/CD [例子](https://github.com/buqiyuan/nest-admin/actions/runs/8341220737/job/22827924001)
https://github.com/buqiyuan/nest-admin/blob/32b83f11100ff0e74270ae06cdd1b6b431e2cdd3/.github/workflows/build-stable.yml#L32-L48
