### ISSUE TITLE
sql文件无法导入

### ISSUE THREAD

**Issue by ryiot** [buqiyuan/nest-admin#4]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/78907118/172006424-7737c1db-e4ef-44ef-81af-82e69ea278de.png">

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- Mysql version:
- Redis version:

**Comment by Sunny-liaokai** [comment]
我的也是

**Comment by buqiyuan** [comment]
🤔MySQL版本是8.x以上吗？

**Comment by ryiot** [comment]
> 🤔MySQL版本是8.x以上吗？

mysql 5.7.x

**Comment by Sunny-liaokai** [comment]
大佬救救。sql文件倒不进去，能重新生成一份sql文件吗，我的版本也是5.7.x

**Comment by Coder-ZhaoLu** [comment]
应该是字符集根数据库不一样才不能导入吧，比如我的就是改成了COLLATE=utf8mb4_general_ci;就导入成功了

**Comment by YuQian2015** [comment]
我遇到Unknown collation: 'utf8mb4_0900_ai_ci'，将 5.7 换成 8.0 可以了。

**Comment by semyin** [comment]
sql文件有误，表建好了，但是insert那里加不进去数据

**Comment by semyin** [comment]
> sql文件有误，表建好了，但是insert那里加不进去数据

INSERT INTO `sys_user_role` VALUES ('2020-09-14 04:10:34.371646','2020-09-14 04:10:34.371646',1,1,1),('2022-07-31 00:07:00.494619','2022-07-31 00:07:00.494619',18,6,2),('2022-09-19 20:25:20.375153','2022-09-19 20:25:20.375153',65,21,4),('2022-09-19 20:25:36.580258','2022-09-19 20:25:36.580258',66,22,3);

**Comment by semyin** [comment]
> > sql文件有误，表建好了，但是insert那里加不进去数据
> 
> INSERT INTO `sys_user_role` VALUES ('2020-09-14 04:10:34.371646','2020-09-14 04:10:34.371646',1,1,1),('2022-07-31 00:07:00.494619','2022-07-31 00:07:00.494619',18,6,2),('2022-09-19 20:25:20.375153','2022-09-19 20:25:20.375153',65,21,4),('2022-09-19 20:25:36.580258','2022-09-19 20:25:36.580258',66,22,3);

实际上第二条数据会报psalt不能为null

> > sql文件有误，表建好了，但是insert那里加不进去数据
> 
> INSERT INTO `sys_user` VALUES ('2020-08-27 03:38:30.000000','2022-03-28 22:52:11.845930',1,1,'路飞','rootadmin','ccdb5f7e5be14fe0c0528974428f79f9','','https://buqiyuan.gitee.io/img/logo.jpg','qa894178522@qq.com','15622472425',NULL,'xQYCspvFb8cAW6GG1pOoUGTLqsuUSO3d',1),('2021-12-07 09:29:18.844687','2022-07-31 00:07:00.332032',6,2,'路飞','luffyfe','a201c32f60232acaf95d9eb74926c8aa','草帽小子',NULL,'[1687646846@qq.com](mailto:1687646846@qq.com)','1355355646','嘿嘿嘿','WdE7MrslDYt02ZNkGo4asBhpXXY57wzi',1),('2022-09-19 20:25:20.362095','2022-09-19 20:25:20.362095',21,5,'543253245','lamp523453','49b28678aac0064f38a881b1e6b0a644',NULL,NULL,'','','','IC2yKu1eWyM4lwmholpLgftFZVtBozmX',1),('2022-09-19 20:25:36.573561','2022-09-19 20:25:36.573561',22,2,'3425253','lamp555','cef7a31ba95492a376ef4dd5e56a7610',NULL,NULL,'','','','QRMRwVfZWCQXv9kCdCgTs5wKWNjdNEFn',1);

实际上第三条就会报psalt不能为null
