### ISSUE TITLE
OpenAPI 关于200的响应模型

### ISSUE THREAD

**Issue by ppxb** [buqiyuan/nest-admin#56]
## Bug report（问题描述）
在学习源码的时候发现对OpenAPI的响应做了封装。其中200的响应是在哪儿实现的呢？

#### Steps to reproduce（问题复现步骤）
None

#### Screenshot or Gif（截图或动态图）
![微信截图_20240604145409](https://github.com/buqiyuan/nest-admin/assets/17081240/9addcf4e-8f11-4313-84ae-3ec67e53ce7e)

#### Link to minimal reproduction（最小可在线还原demo）

None

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- Mysql version:
- Redis version:

**Comment by buqiyuan** [comment]
你说的是 201 吗？GET 默认是 200，POST 默认是 201
https://github.com/buqiyuan/nest-admin/blob/0cae4e928e27591864fc80c2216978575c047814/src/common/decorators/api-result.decorator.ts#L67-L71

因为`NestJS Swagger CLI`插件使用静态分析来确定是否在特定路由上设置了自定义 HTTP 状态。如果没有，则会自动应用 201（默认值），然而封装的 `@ApiResult`(applyDecorators) 是一个运行时构造 - 因此通过该函数应用的装饰器不会被插件检查。
官方相应源码：
https://github.com/nestjs/swagger/blob/61fdb23b28113c09a334267b674e15a71d2da786/lib/plugin/visitors/controller-class.visitor.ts#L411-L420
<img width="815" alt="image" src="https://github.com/buqiyuan/nest-admin/assets/39730999/fd026e50-8589-49f8-aee3-ad31a286d2fc">

**Comment by buqiyuan** [comment]
优化了下，现在不会额外多出一个 `default`的响应了
<img width="839" alt="image" src="https://github.com/buqiyuan/nest-admin/assets/39730999/a16f9b12-4fcc-4a79-9d81-904617e8eace">
**相关代码变动：**
https://github.com/buqiyuan/nest-admin/blob/9782f647102f524d77387f8ded03e1a180f896df/src/common/decorators/api-result.decorator.ts#L68-L94

**Comment by ppxb** [comment]
🫡，感谢
