### ISSUE TITLE
项目中2 处注册了限流(ThrotterModule)，这样是否会有问题？

### ISSUE THREAD

**Issue by meraydao** [buqiyuan/nest-admin#63]
#### Screenshot or Gif（截图或动态图）
![image](https://github.com/user-attachments/assets/5513b82d-b8ed-4f87-a322-6456c6619f9b)
![image](https://github.com/user-attachments/assets/f26f242d-1e86-42cc-8202-d3fed2a86022)

#### Other relevant information（格外信息）
- Your OS:
- Node.js version:
- Mysql version:
- Redis version:

**Comment by buqiyuan** [comment]
感谢指出！去掉一个就好了，重复注册，后者的配置会覆盖前者的配置
