### ISSUE TITLE
用户管理提示：ThrottlerException: Too Many Requests

### ISSUE THREAD

**Issue by ren2672** [buqiyuan/nest-admin#66]
## Bug report（问题描述）
点击用户管理，并点击几个分部，大概切换没几下 就提示ThrottlerException: Too Many Requests
#### Screenshot or Gif（截图或动态图）
![image](https://github.com/user-attachments/assets/fae55303-81fd-4d2c-8297-584ff247b083)
![image](https://github.com/user-attachments/assets/74e57b4d-60dc-46a9-8819-fc2fe028180f)

#### Other relevant information（格外信息）
- Your OS:用的官方网址测试的
- Node.js version:
- Mysql version:
- Redis version:

**Comment by zyellen** [comment]
我也是 刷新几次就会 自能重启服务器解决

**Comment by wanghao1991** [comment]
作者用了 速率限制，防止暴力请求！
![微信图片_20240918180246](https://github.com/user-attachments/assets/bdf801e6-5792-4f38-ab9c-1fd4a62c6f55)

**Comment by zyellen** [comment]
ThrottlerModule.forRoot([
      {
        limit: 10, // 请求次数限制
        ttl: 6000, // 时间窗口
      },
    ]) 这边根据项目需求修改就可以
