### ISSUE TITLE
请问一下，怎么新建权限字符串

### ISSUE THREAD

**Issue by yyrjlw** [buqiyuan/nest-admin#9]
### 新建菜单权限的时候，权限字符串是从下拉列表选择的。那怎样新建权限字符串呢？

![](https://p0.meituan.net/dpplatform/d81e01a98c4654733ee0b30a7d69487325122.png)

**Comment by buqiyuan** [comment]
权限字符串是跟后端接口挂钩的，暂不支持用户新增自定义权限字符串。要新增权限勾选项的话，需要在开发者前端如下图定义权限与接口的关系，而用户则只能自由勾选已有的权限。
<img width="974" alt="image" src="https://github.com/buqiyuan/nest-admin/assets/39730999/9af23b7f-273a-4744-b696-48ec7ac17776">
